### ISSUE TITLE
Unknown config object 'print_stats'

### ISSUE THREAD

**Issue by manuelcribeiro** [0xD34D/klipper_ender3_v3_se#24]
I'm having this issue on a brand new instalation:
Unhandled exception during ready callback
Traceback (most recent call last):
  File "/home/manuel/klipper/klippy/klippy.py", line 205, in _connect
    cb()
  File "/home/manuel/klipper/klippy/extras/e3v3se_display.py", line 589, in handle_ready
    self.pd.handle_ready()
  File "/home/manuel/klipper/klippy/extras/printerInterface.py", line 167, in handle_ready
    self.update_variable()
  File "/home/manuel/klipper/klippy/extras/printerInterface.py", line 334, in update_variable
    self.job_Info = self.printer.lookup_object(
  File "/home/manuel/klipper/klippy/klippy.py", line 97, in lookup_object
    raise self.config_error("Unknown config object '%s'" % (name,))
configparser.Error: Unknown config object 'print_stats'
Transition to shutdown state: Internal error during ready callback: Unknown config object 'print_stats'

**Comment by AaronMickDee** [comment]
Same. Has to do with the e3v3 display support. After commenting that part of the printer.cfg out it works.
